<?php

namespace H\CocktailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CocktailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CocktailRepository extends EntityRepository
{
}
